<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>springseed.xml</string>
	</array>
	<key>firstLineMatch</key>
	<string>&lt;\!--springseed--&gt;</string>
	<key>foldingStartMarker</key>
	<string>^\s*(&lt;[^!?%/](?!.+?(/&gt;|&lt;/.+?&gt;))|&lt;[!%]--(?!.+?--%?&gt;)|&lt;%[!]?(?!.+?%&gt;))</string>
	<key>foldingStopMarker</key>
	<string>^\s*(&lt;/[^&gt;]+&gt;|[/%]&gt;|--&gt;)\s*$</string>
	<key>keyEquivalent</key>
	<string>^~X</string>
	<key>name</key>
	<string>Springseed XML</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>&lt;[!%]--</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.xml.springseed</string>
				</dict>
			</dict>
			<key>end</key>
			<string>--%?&gt;</string>
			<key>name</key>
			<string>comment.block.xml.springseed</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(\{)</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.actionscript-prop.begin.springseed</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>TODO: Solve how to reference #actionScriptProperties </string>
			<key>end</key>
			<string>(\})</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.actionscript-prop.end.springseed</string>
				</dict>
			</dict>
			<key>name</key>
			<string>storage.actionscript.embedded.springseed</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#invalid</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#springSeedSubstitutions</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(&lt;AddressMapNode)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.address-map-node.xml.springseed</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(/?&gt;)</string>
			<key>name</key>
			<string>meta.tag.address-map-node.xml.springseed</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#tagStuff</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(&lt;AddressMapDataProvider)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.address-map-data-provider.xml.springseed</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(/?&gt;)</string>
			<key>name</key>
			<string>meta.tag.address-map-data-provider.xml.springseed</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#tagStuff</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(&lt;LoadAddressSpace)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.load-address-space.xml.springseed</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(/?&gt;)</string>
			<key>name</key>
			<string>meta.tag.load-address-space.xml.springseed</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#tagStuff</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(&lt;UriDependency)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.uri-dependency.xml.springseed</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(/?&gt;)</string>
			<key>name</key>
			<string>meta.tag.uri-dependency.xml.springseed</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#tagStuff</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(&lt;/?)(?:([-_a-zA-Z0-9]+)((:)))?([-_a-zA-Z0-9:]+)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.xml.springseed</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.namespace.xml.springseed</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.xml.springseed</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>punctuation.separator.namespace.xml.springseed</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.localname.xml.springseed</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(/?&gt;)</string>
			<key>name</key>
			<string>meta.tag.xml.springseed</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#tagStuff</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>include</key>
			<string>text.xml</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>actionScriptProperties</key>
		<dict>
			<key>begin</key>
			<string>\{</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.actionscript-prop.begin.springseed</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>TODO "namespace", ".", and "relative" matches.</string>
			<key>end</key>
			<string>\}</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.actionscript-prop.end.springseed</string>
				</dict>
			</dict>
			<key>name</key>
			<string>source.actionscript-props.embedded.springseed</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#springSeedSubstitutions</string>
				</dict>
			</array>
		</dict>
		<key>doublequotedString</key>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.xml.springseed</string>
				</dict>
			</dict>
			<key>end</key>
			<string>"</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.xml.springseed</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.double.xml.springseed</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#actionScriptProperties</string>
				</dict>
			</array>
		</dict>
		<key>invalid</key>
		<dict>
			<key>name</key>
			<string>invalid.illegal</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>POP</string>
				</dict>
			</array>
		</dict>
		<key>singlequotedString</key>
		<dict>
			<key>begin</key>
			<string>'</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.xml.springseed</string>
				</dict>
			</dict>
			<key>end</key>
			<string>'</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.xml.springseed</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.single.ant</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#actionScriptProperties</string>
				</dict>
			</array>
		</dict>
		<key>springSeedSubstitutions</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.actionscript.embedded.namespace.springseed</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>storage.actionscript.embedded.seperator.springseed</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>storage.actionscript.embedded.localname.springseed</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Matching namespace and localname</string>
			<key>match</key>
			<string>(?:([_a-zA-Z0-9\.]+)((:)))?([_a-zA-Z0-9:\.]+)</string>
		</dict>
		<key>tagStuff</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.other.attribute-name.namespace.xml.springseed</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.other.attribute-name.xml.springseed</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.separator.namespace.xml.springseed</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>entity.other.attribute-name.localname.xml.springseed</string>
						</dict>
					</dict>
					<key>match</key>
					<string> (?:([-_a-zA-Z0-9]+)((:)))?([_a-zA-Z-]+)=</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#doublequotedString</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#singlequotedString</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>text.xml.springseed</string>
	<key>uuid</key>
	<string>B44E6E1C-6CEF-486F-8F52-A5234A1A5C40</string>
</dict>
</plist>
